import Head from "next/head";
import { useState, useEffect } from "react";
import { getCharacters } from "utils/utils";

const About = () => {
  // const { data } = fetchCharacters();
  const [data, setData] = useState();

  useEffect(() => {
    const fetchedData = async () => {
      const data = await getCharacters();

      setData(data);
    };

    fetchedData();
  }, []);

  console.log("characters:", data);

  return (
    <>
      <Head>
        <title>MARVEL | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.ico" />
      </Head>
      <h1>About</h1>
      <p>Fetch Characters Test Site</p>
    </>
  );
};

export default About;
