import { useEffect, useState } from "react";
import { getCharacter } from "lib/utils";
import Head from "next/head";
import Grid from "components/Grid";
import Card from "components/Card";
import useFavorites from "hooks/useFavorites";

const IMG_SIZE = "standard_large";

const Favorites = () => {
  const [hero, setHero] = useState([]);
  const { favorites, toggleFavorite, deleteAll } = useFavorites();

  useEffect(() => {
    const fetchCharacter = async () => {
      const heroData = favorites.map(async (key) => {
        return await getCharacter(key);
      });
      setHero(await Promise.all(heroData));
    };

    fetchCharacter();
  }, [favorites.length]);

  const favoriteCharacters = hero.map((hero) => {
    return (
      <Card
        isFavorited={favorites.includes(hero?.id)}
        toggleFavorite={() => toggleFavorite(hero?.id)}
        key={hero.id}
        name={hero.name}
        id={hero.id}
        tumbnail={`${hero.thumbnail.path}/${IMG_SIZE}.${hero.thumbnail.extension}`}
      />
    );
  });

  return (
    <>
      <Head>
        <title>MARVEL | Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.ico" />
      </Head>
      <>
        <h1 className="uppercase text-xl my-6 text-center">
          Favorite Characters
        </h1>
        <Grid items={hero} removeHandler={deleteAll}>
          {favoriteCharacters}
        </Grid>
      </>
    </>
  );
};

export default Favorites;
