import Head from "next/head";

const Favorites = () => {
  return (
    <>
      <Head>
        <title>MARVEL | Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.ico" />
      </Head>
      <h1>Favorites</h1>
    </>
  );
};

export default Favorites;
