import { useState } from "react";

import Head from "next/head";
import SearchBar from "components/SearchBar";
import GridList from "components/GridList";
import Card from "components/Card";
import ReactPaginate from "react-paginate";

const IMG_SIZE = "standard_large";

export default function Home() {
  const [data, setData] = useState([]);
  const [pageNum, setPageNum] = useState(0);

  const usersPerPage = 10;
  const pagesVisited = pageNum * usersPerPage;

  const displayUsers = data
    .slice(pagesVisited, pagesVisited + usersPerPage)
    .map((hero) => {
      return (
        <Card
          key={hero.id}
          name={hero.name}
          id={hero.id}
          tumbnail={`${hero.thumbnail.path}/${IMG_SIZE}.${hero.thumbnail.extension}`}
        />
      );
    });

  const pageCount = Math.ceil(data.length / usersPerPage);
  const changePage = ({ selected }) => {
    setPageNum(selected);
  };

  return (
    <>
      <Head>
        <title>MARVEL | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <h1 className="uppercase text-xl mb-6 text-center">
          Discover Marvel Characters
        </h1>
        <SearchBar placeholder={"Browse Marvel Characters"} setter={setData} />
        <GridList>{displayUsers}</GridList>
        <ReactPaginate
          pageCount={pageCount}
          onPageChange={changePage}
          containerClassName="border border-black flex gap-1 m-2 p-2"
        />
      </div>
    </>
  );
}
