import { useState } from "react";

import Head from "next/head";
import SearchBar from "components/SearchBar";
import GridList from "components/GridList";
import Card from "components/Card";

const IMG_SIZE = "standard_large";

export default function Home() {
  const [data, setData] = useState([]);
  console.log(data.data?.thumbnail);

  let cards;

  if (data) {
    cards = data.map((item) => {
      return (
        <Card
          name={item.name}
          id={item.id}
          tumbnail={`${item.thumbnail.path}/${IMG_SIZE}.${item.thumbnail.extension}`}
        />
      );
    });
  }

  return (
    <>
      <Head>
        <title>MARVEL | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <h1 className="uppercase text-xl mb-6">Discover Marvel Characters</h1>
        <SearchBar placeholder={"Search..."} setter={setData} />
        <GridList>{cards ? cards : ""}</GridList>
      </div>
    </>
  );
  console.log(thumbnail);
}
