import { useState } from "react";
import Head from "next/head";
import SearchBar from "components/SearchBar";
import Grid from "components/Grid";
import Card from "components/Card";

const IMG_SIZE = "standard_large";

export default function Home() {
  const [hero, setHero] = useState([]);

  const heroCardsList = hero.map((hero) => {
    return (
      <Card
        key={hero.id}
        name={hero.name}
        id={hero.id}
        tumbnail={`${hero.thumbnail.path}/${IMG_SIZE}.${hero.thumbnail.extension}`}
      />
    );
  });

  return (
    <>
      <Head>
        <title>MARVEL | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.ico" />
      </Head>
      <>
        <h1 className="uppercase text-xl my-6 text-center">
          Discover Marvel Characters
        </h1>
        <SearchBar placeholder={"Browse Marvel Characters"} setter={setHero} />
        <Grid items={hero}>{heroCardsList ? heroCardsList : ""}</Grid>
      </>
    </>
  );
}
